### ISSUE TITLE
Indigo hack - File screen and saving is broken.

### ISSUE THREAD

**Issue by BruceShankleIV** [pj64team/Project64-Legacy#131]
https://youtu.be/m8ZE7kmS-JE

This is an OoT romhack called indigo, can be found here: https://github.com/krm01/oot-indigo-mod/releases/tag/v0.3.16

here is what we see: The file select does not display properly until you have a save file in file 1. Specifically, the screen is not updating. Once you have a file in file 1, the screen updates, but if you ever save the game while playing, your save file becomes deleted. this romhack works on N64 so something is up here. this was also an issue in the OG 1.6 as well.

**Comment by TheGent** [comment]
Ok so what you are saying is, you can make a save initially and play in-game, but as soon as you make an internal save (Start and then Be Button and Save) and rest. You can no longer view the save menu until you press A button and forced to create a new file right? And when you say this works on the real hardware, did you use a flashcard and try yourself? or a Everdrive that relies on Software assistance?

**Comment by TheGent** [comment]
Ok i just tried this on real hardware using RetroBlaster and it does indeed work.

It does have an issue in the Original 1.6 & Legacy that a initial game save can be created but once you in-gmae save  (Start,B-Button-Save) and reset you have a black screen where the File screen is and until you press A you do not see anything & you are forced to create a new file

**Comment by BruceShankleIV** [comment]
Yeah, screen is at first black because it is not updating. The reason you reset and the screen is black is because you saved the game on file 1, and doing that caused the file to be deleted. When there is no file 1 (it hasn't been created or it has been deleted), then that is when the screen does not update. To test this, you could make a file 1, and then make a file on any other save file and get through the intro, save and reset, and the screen will probably still update properly because you have a file in file 1.

Also, in case the creator knows info about this, he is on discord. He can be reached by friend requesting the username "kentonm".

I also don't think this happens on other emulators so this is exclusive to old PJ64 it looks like. I tested briefly with mupen64 and it didnt have this issue.

**Comment by TheGent** [comment]
Yes confirmed to work on Mupen64, Ares, Zils hmmmmmmmm

**Comment by BruceShankleIV** [comment]
Suddenly, for no explainable reason whatsoever, the screen is no longer failing to update in Project64 legacy. I have no idea why it is updating now, but the screen is now updating even when there is no file in file 1.

However, maybe me recently installing a bunch of visual studio redistributable had something to do with it? I'm not quite sure.

Save problem still exists though, so it seems like that is not connected to the screen updating issue.

**Comment by BruceShankleIV** [comment]
Ok I tried something in Project64 1.6, it seems like setting the Save Type to FlashRam in the rom settings seems to get rid of the screen updating issue.

**Comment by TheGent** [comment]
> Ok I tried something in Project64 1.6, it seems like setting the Save Type to FlashRam in the rom settings seems to get rid of the screen updating issue.

That's strange seeming as the save it creates is a SRAM save type
