### ISSUE TITLE
Jabo Legacy Input setup mode breaks if you input it too fast.

### ISSUE THREAD

**Issue by BruceShankleIV** [pj64team/Project64-Legacy#132]
Normally, there are no issues with the setup mode. However, if you key in your inputs quickly, then the input you put for c-left ends up being applied to c-up, and if you continue messing with it you can get various results. I would recommend either fixing the setup mode (which probably isn't possible because I think jabo input is closed-source), or remove the setup option entirely.

https://youtu.be/S-X5xEGatTA

**Comment by TheGent** [comment]
Yea, there isn't anything we can do about jabo plugins like this, but the NRage Legacy source is available here: https://github.com/pj64team/NRage-Legacy-Input if anyone wants to take a bash at adding a setup function?
