### ISSUE TITLE
Selecting "Choose Rom Directory..." causes the emulator to hang if Azimer's audio plugin is used

### ISSUE THREAD

**Issue by Fanatic-64** [pj64team/Project64-Legacy#29]
Steps to reproduce:
Make sure "Azimer's Legacy Audio v0.70.10" is the currently selected audio plugin.
Go to the File menu and select "Choose Rom Directory...", or go to Options - >Settings... -> Directories and click on any of the "..." buttons to browse to a custom path.
(Note that a ROM does **not** have to be running to reproduce this problem.)
Result:
The emulator hangs indefinitely (spinning circle cursor and "(Not Responding)" label on title bar).
Expected result:
The emulator should not hang, and the Browse For Folder window should appear.

This problem doesn't happen if an audio plugin other than Azimer's Legacy Audio v0.70.10 is being used. This problem also doesn't happen when Azimer's Legacy Audio v0.70.10 is used in the original Project64 1.6.

**Comment by Fanatic-64** [comment]
Addendum: The problem only happens when the Backend Sound Driver in the settings of Azimer's is set to XAudio 2 Driver (the default option), XAudio 2 Legacy Driver or WASAPI Driver (experimental).

**Comment by TheGent** [comment]
For now the newer version Azimer's Legacy Audio v0.70.10.a has Direct Audio as default to combat this issue.

**Comment by TheGent** [comment]
This has now been resolved with a new Audio and Application update
