### ISSUE TITLE
Battle Tanks Global assult: Looping at intro

### ISSUE THREAD

**Issue by Nes-player4Life** [pj64team/Project64-Legacy#33]
Game loops to logos when start is pressed. 1.6.2 Alpha

**Comment by TheGent** [comment]
What version/Versions of the game is this?
What plugins are you using?
What are the Rom Settings?
Can you add images of them please?

Also are you using any cheats that might need to be enabled in game?

**Comment by Nes-player4Life** [comment]
local setting was wrong. was using the old rsp.
