### ISSUE TITLE
Can't create a temporary rom file warning

### ISSUE THREAD

**Issue by TheGent** [pj64team/Project64-Legacy#85]
![Temp_rom2](https://github.com/pj64team/Project64-Legacy/assets/82123790/4600787e-e1ca-488f-975d-e32f9ed25863)
It looks like when 2 instances are ran, there is an error saying it can't create a temporary rom file on the second instance.

@hacktarux and myself have both witnessed this several times.

To reproduce, just start a game and then open another Project64_1.6.2.exe and launch another game from the browser.
It will resault in the warning as shown in the image.

It does not matter what the second game is, it can be a different one to the first or the same.

**Comment by parasyte** [comment]
Should be fixed by #100! @TheGent can you check this one?

**Comment by TheGent** [comment]
> Should be fixed by #99! @TheGent can you check this one?

Yup it does indeed fix it 👍
